### ISSUE TITLE
Yo angular-basic command is not working.

### ISSUE THREAD

**Issue by marcore86** [MattJeanes/AngularBasic#11]
sudo yo angular-basic on mac is not working, pls find below log:

yo angular-basic

/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:47
  _storeAsModule(namespace, Generator, resolved = 'unknown') {
                                                ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:13:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
apples-MacBook-Pro:Fitness marco$ sudo yo angular-basic
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:47
  _storeAsModule(namespace, Generator, resolved = 'unknown') {

npm -v 3.8.6
node -v 4.4.3
macOs High Sierra

**Comment by AmyJeanes** [comment]
Hi Marcore, looking at your npm and node versions - you appear to be way behind. This project was designed and tested against these versions:

```
PS C:\Users\Matt> node --version
v8.9.4
PS C:\Users\Matt> yarn --version
1.7.0
PS C:\Users\Matt> npm --version
5.4.2
```

From the error message, it would appear to a yeoman internal error rather than an error while generating this `angular-basic` project, looks to be related to your version of Node/JavaScript not understanding newer javascript syntax e.g. let/const/class etc

Additionally, I'm not sure that this project works against anything lower than Node 8.9 due to Angular 6/Webpack 4 compatibility, 

Hope that helps! 😄

**Comment by marcore86** [comment]
Hi Matt, 
you were right, was silly to try that with an old node version.
Command perfectly worked on latest one.

Cheers
